project:
  type: book

lang: pt-BR

book:
  title: "eprv2"
  author: "Darren Norris"
  date: "6/15/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - map.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf]
  cover-image: "cover.jpg"
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    geometry:
      - top=30mm
      - left=25mm
      - right=25mm
      - bottom=30mm
    fig-pos: "H"
    include-before-body:
      - text: |
          \begin{titlepage}
          \centering
          \vspace*{1cm}
          \includegraphics[width=\textwidth,height=0.85\textheight,keepaspectratio]{cover.jpg}
          \end{titlepage}

editor: visual

