project:
  type: book

lang: pt-BR

book:
  title: "Ecologia de Paisagens com R"
  output-file: "eprv2"
  author: "Darren Norris"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - map.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf]
  repo-url: "https://github.com/darrennorris/eprv2"
  repo-actions: [source]
  cover-image: "cover.jpg"
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-newwindow: true
  pdf:
    pdf-engine: lualatex
    documentclass: scrreprt
    geometry:
      - top=30mm
      - left=25mm
      - right=25mm
      - bottom=30mm
    fig-pos: "H"
    include-in-header:
      - text: |
          \makeatletter
          \renewcommand{\maketitle}{
            \begin{titlepage}
              \centering
              \vspace*{1cm}
              % 1. The Title
              {\Huge\bfseries \@title \par}
              \vspace{1.5cm}
              
              % 2. The Cover Image
              % Note: Height is restricted to 60% of the page so it doesn't push the author text off the bottom.
              \includegraphics[width=\textwidth,height=0.6\textheight,keepaspectratio]{cover.jpg} \par
              \vspace{1.5cm}
              
              % 3. The Author and Date
              {\Large \@author \par}
              \vspace{0.5cm}
              {\large \@date \par}
            \end{titlepage}
            
            % Keeps the Table of Contents from having page numbers
            \pagenumbering{gobble} 
          }
          \makeatother

editor: visual

